import Navbar from './components/navbar/Navbar';
import { Noto_Sans_Mono } from 'next/font/google'
import "./globals.css";

const noto = Noto_Sans_Mono({ subsets: ["latin"], weight: '400' });

export const metadata = {
  title: "Will Koenig",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={noto.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
